# Generated by Django 3.2.7 on 2021-09-30 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banks',
            options={'ordering': ['compensation_code'], 'verbose_name': 'Bank', 'verbose_name_plural': 'Banks'},
        ),
    ]
