BEGIN TRANSACTION;
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 'Banco do Brasil S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3, 'Banco da Amazonia S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4, 'Banco do Nordeste do Brasil S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 12, 'Banco Standard de Investimentos S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 14, 'Natixis Brasil S.A. Banco Múltiplo');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 19, 'Banco Azteca do Brasil S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 21, 'Banestes S.A. Banco do Estado do Espírito Santo S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 24, 'Banco de Pernambuco S.A. – BANDEPE');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 25, 'Banco Alfa S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 29, 'Banco Banerj S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 31, 'Banco Beg S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 33, 'Banco Santander (Brasil) S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 36, 'Banco Bradesco BBI S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 37, 'Banco do Estado do Pará S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 40, 'Banco Cargil S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 41, 'Banco do Estado do Rio Grade do Sul S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 44, 'Banco BVA S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 45, 'Banco Opportunity S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 47, 'Banco do Estado de Sergipe S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 62, 'Hipercard Banco Múltiplo S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 63, 'Banco IBI S.A. – Banco Múltiplo');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 65, 'Banco Lemon S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 66, 'Banco Morgan Stanley S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 69, 'BPN Brasil Banco Múltiplo S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 70, 'BRB – Banco de Brasilia S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 72, 'Banco Rural Mais S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 73, 'BB Banco Popular do Brasil S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 74, 'Banco J. Safra S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 75, 'Banco CR2 S/A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 76, 'Banco KEB do Brasil S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 77, 'Banco Inter S/A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 78, 'BES Investimentos do Brasil S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 79, 'JBS Banco S/A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 81, 'Concórdia Banco S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 82, 'Banco Topázio S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 83, 'Banco da China Brasil S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 96, 'Banco BM&F de Serviços de Liquidação e Custodia S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 104, 'Caixa Econômica Federal');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 107, 'Banco BBM S/A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 151, 'Banco Nossa Caixa S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 184, 'Banco Itaú BBA S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 204, 'Banco Bradesco Cartões S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 208, 'Banco UBS Pactual S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 212, 'Banco Matone S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 213, 'Banco Arbi S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 214, 'Banco Dibens S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 215, 'Banco Comercial e de Investimento Sudameris S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 217, 'Banco John Deere S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 218, 'Banco Bonsucesso S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 222, 'Banco Calyon brasil S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 224, 'Banco Fibra S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 225, 'Banco Brascan S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 229, 'Banco Cruzeiro Do Sul S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 230, 'Unicard Banco Múltiplo S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 233, 'Banco GE Capital S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 237, 'Banco Bradesco S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 241, 'Banco Classico S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 243, 'Banco Máxima S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 246, 'Banco ABC Brasil S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 248, 'Banco Boavista Interatlantico S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 249, 'Banco Investicred Unibanco S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 250, 'Banco Schahin S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 254, 'Paraná Banco S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 263, 'Banco Cacique S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 265, 'Banco Fator S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 266, 'Banco Cedula S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 300, 'Banco de La Nacion Argentina');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 318, 'Banco BMG S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 320, 'Banco Industrial e Comercial S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 341, 'Banco Itaú S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 366, 'Banco Societé Generale Brasil S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 370, 'Banco Westlb do Brasil S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 376, 'Banco J.P. Morgan S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 389, 'Banco Mercantil do Brasil S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 394, 'Banco Finasa BMC S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 399, 'HSBC Bank Brasil S.A. – Banco Múltiplo');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 409, 'Unibanco-União de Bancos Brasileiros S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 412, 'Banco Capital S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 422, 'Banco Safra S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 453, 'Banco Rural S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 456, 'Banco de Tokyo-Mitsubishi UFJ Brasil S/A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 464, 'Banco Sumitomo Mitsui Brasileiro S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 473, 'Banco Caixa Geral – Brasil S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 477, 'Citibank N.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 479, 'Banco Itaubank S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 487, 'Deutsche Bank S.A. – Banco Alemao');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 488, 'JPMorgan Chase Bank - National Association');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 492, 'Ing Bank N.V.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 494, 'Banco de la Republica Oriental del Uruguay');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 495, 'Banco de la Provincia de Buenos Aires');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 505, 'Banco Credit Suisse (Brasil) S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 600, 'Banco Luso Brasileiro S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 604, 'Banco Industrial Do Brasil S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 610, 'Banco VR S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 611, 'Banco Paulista S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 612, 'Banco Guanabara S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 613, 'Banco Pecunia S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 623, 'Banco Panamericano S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 626, 'Banco Ficsa S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 630, 'Banco Intercap S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 633, 'Banco Rendimento S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 634, 'Banco Triangulo S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 637, 'Banco Sofisa S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 638, 'Banco Prosper S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 641, 'Banco Alvorada S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 643, 'Banco Pine S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 652, 'Itaú Unibanco Banco Múltiplo S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 653, 'Banco Indusval S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 654, 'Banco A.J. Renner S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 655, 'Banco Votorantim S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 707, 'Banco Daycoval S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 719, 'Banif – Banco Internacional do Funchal (Brasil) S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 721, 'Banco Credibel S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 734, 'Banco Gerdau S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 735, 'Banco Pottencial S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 738, 'Banco Morada S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 739, 'Banco BGN S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 740, 'Banco Barclays S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 741, 'Banco Ribeirao Preto S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 743, 'Banco Semear S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 745, 'Banco Citibank S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 746, 'Banco Modal S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 747, 'Banco Rabobank International Brasil S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 748, 'Banco Cooperativo Sicredi S.A.');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 749, 'Banco Simples S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 751, 'Dresdner Bank Brasil S.A. Banco Multiplo');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 752, 'Banco BNP Paribas Brasil S.A');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 753, 'NBC Bank Brasil S. A. – Banco Múltiplo');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 756, 'Banco Cooperativo do Brasil S.A. – Bancoob');
INSERT INTO "BANKS" (created_at, updated_at, compensation_code, institution_name) VALUES (CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 757, 'Banco KEB do Brasil S.A.');
COMMIT;
